config:
  # is automatically ignored when custom-checks.jar is on the classpath
  # however other CI checks use the argsfile where our plugin is not applied
  # we need to care take of this by explicitly allowing this properties
  excludes: 'custom-checks.*'

custom-checks:
  active: true
  SpekTestDiscovery:
    active: true
    includes: ['**/test/**/*Spec.kt']

comments:
  CommentOverPrivateProperty:
    active: true
  UndocumentedPublicClass:
    active: true
    excludes: ['**/*.kt']
    includes: ['**/domain/**/*.kt']
  UndocumentedPublicFunction:
    active: true
    excludes: ['**/*.kt']
    includes: ['**/i*/**/*.kt']

complexity:
  StringLiteralDuplication:
    active: true
    excludes: ['**/test/**', '**/*Test.kt', '**/*Spec.kt']
    threshold: 5
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: '$^'
  ComplexInterface:
    active: true
    threshold: 10
    includeStaticDeclarations: false
    includePrivateDeclarations: false
  ComplexMethod:
    active: true
    ignoreSingleWhenExpression: true
  LargeClass:
    active: true
    excludes: ['**/test/**', '**/*.Test.kt', '**/*.Spec.kt']
  MethodOverloading:
    active: true
  ComplexCondition:
    active: true

exceptions:
  NotImplementedDeclaration:
    active: true
  InstanceOfCheckForException:
    active: true
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
  ThrowingNewInstanceOfSameException:
    active: true

formatting:
  active: true
  android: false
  autoCorrect: true
  AnnotationSpacing:
    active: true
  EnumEntryNameCase:
    active: true
  ImportOrdering:
    active: true
  Indentation:
    active: true
  MaximumLineLength:
    active: false
  NoEmptyFirstLineInMethodBlock:
    active: true
  ParameterListWrapping:
    active: false
  SpacingAroundAngleBrackets:
    active: true
  SpacingAroundDoubleColon:
    active: true
  SpacingAroundUnaryOperator:
    active: true
  SpacingBetweenDeclarationsWithAnnotations:
    active: true
  SpacingBetweenDeclarationsWithComments:
    active: true

potential-bugs:
  UnsafeCast:
    active: true
    excludes: ['**/test/**', '**/*.Test.kt', '**/*.Spec.kt']
  UselessPostfixExpression:
    active: true
  DoubleMutabilityForCollection:
    active: true
  HasPlatformType:
    active: true
    excludes: ['**/f-*/**', '**/f_*/**', '**/cf-*/**', '**/cf_*/**']
  InvalidRange:
    active: true
  MapGetWithNotNullAssertionOperator:
    active: true
  UnnecessaryNotNullOperator:
    active: true

style:
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true
  ExplicitItLambdaParameter:
    active: true
  ForbiddenComment:
    active: true
    values: ['TODO:', 'FIXME:', 'STOPSHIP:', 'WIP']
  LibraryCodeMustSpecifyReturnType:
    active: true
    excludes: ['**/*.kt']
    includes: ['**/i*/**/*.kt']
  MaxLineLength:
    active: true
    excludes: ['**/test/**', '**/*Test.kt', '**/*Spec.kt']
    excludeCommentStatements: true
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreEnums: true
    ignoreNumbers: ['-1', '0', '1', '2', '100', '1000']
    excludes: [ '**/test/**', '**/*Test.kt', '**/*Spec.kt' ]
  NestedClassesVisibility:
    active: true
  PreferToOverPairSyntax:
    active: true
  RedundantVisibilityModifierRule:
    active: true
  ReturnCount:
    active: true
    excludeGuardClauses: true
  SafeCast:
    active: true
  SpacingBetweenPackageAndImports:
    active: true
  UnnecessaryApply:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  UnusedImports:
    active: true
  UnusedPrivateMember:
    active: true
    allowedNames: '(_|ignored|expected)'
  UseCheckOrError:
    active: true
  UseEmptyCounterpart:
    active: true
  UseIfInsteadOfWhen:
    active: true
  UseIsNullOrEmpty:
    active: true