requiredParams:
  name: InteractorModule
  description: Creates empty i-module.

optionalParams:
  revision: 1
  category: Surf
  formFactor: mobile
  constraints:
    - kotlin
  screens:
    - new_module
    - menu_entry
  minApi: 7
  minBuildApi: 8

widgets:
  - stringParameter:
      id: interactorModuleNameWithoutPrefix
      name: Имя модуля без префикса i-. Внимание, обновлять settings.gradle нужно вручную
      help: The name of the screen to create
      constraints:
        - module
        - nonempty
      default: blank

  - stringParameter:
      id: moduleName
      name: Название модуля
      help: module name
      constraints:
        - nonempty
      default: i-${interactorModuleNameWithoutPrefix}
      suggest: i-${interactorModuleNameWithoutPrefix}

  - stringParameter:
      id: package
      name: Название пакета
      help: Package name (com.example.ru)
      constraints:
        - app_package
        - nonempty
      default: com.example.ru

  - stringParameter:
      id: slashedPackageName
      name: Название пакета со слешами вместо точек (com/example/ru)
      help: Package name with slashes instead of dots (com/example/ru)
      constraints:
        - nonempty
      default: com/example/ru

recipe:
  - instantiate:
      from: /root/build.gradle.ftl
      to: ${moduleName}/build.gradle
  - instantiate:
      from: root/AndroidManifest.xml.ftl
      to: ${moduleName}/src/main/AndroidManifest.xml
  #      т.к. библиотека не поддерживает создание пустых директорий, приходится создавать хотя бы один файл внутри модуля
  - instantiateAndOpen:
      from: root/src/app_package/java/Interactor.kt.ftl
      to: ${moduleName}/src/main/java/${slashedPackageName}/i_${interactorModuleNameWithoutPrefix}/${interactorModuleNameWithoutPrefix.underlinesToCamelCase()}Interactor.kt