name: Pull Request

on:
  pull_request:

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      run: ./gradlew clean assembleQa

    - name: Build template
      if: ${{ !startsWith(github.base_ref, 'project-snapshot') }}
      run: |
        echo "androidStandardDebugDir=${{ github.workspace }}\nandroidStandardDebugMode=true" > template/android-standard/androidStandard.properties
        ./gradlew -p template clean assembleQa assembleRelease --stacktrace

    - name: Run unit tests
      run: ./gradlew testQaUnitTest
